Functional tests: use autotools to choose locations

diff --git a/tests/functional-tests/helper-test-data.sh.in b/tests/functional-tests/helper-test-data.sh.in
--- a/tests/functional-tests/helper-test-data.sh.in
+++ b/tests/functional-tests/helper-test-data.sh.in
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-if [[ ! -e ../../utils/data-generators/cc/generate ]]; then
+if [[ ! -e @topsrcdir@/utils/data-generators/cc/generate ]]; then
     echo "Run this from test/functional-tests/"
     exit 2
 fi
@@ -8,7 +8,7 @@ fi
 # If we don't have ttl files, bring them from the data-generators
 if [[ ! -d ttl ]]; then
    CURRENT=`pwd`
-   cd ../../utils/data-generators/cc
+   cd @topsrcdir@/utils/data-generators/cc
    # Generation takes time. Don't ask if they are already generated.
    #  Checking just one random .ttl file... not good
    if [[ ! -e ttl/032-nmo_Email.ttl ]]; then
@@ -18,7 +18,7 @@ if [[ ! -d ttl ]]; then
    fi
    cd $CURRENT
    echo "Moving ttl generated files to functional-tests folder"
-   cp -R ../../utils/data-generators/cc/ttl . || (echo "Error generating ttl files" && exit 3)
+   cp -R @topsrcdir@/utils/data-generators/cc/ttl . || (echo "Error generating ttl files" && exit 3)
 else
    echo "TTL files already in place"
 fi
